# .goreleaser.yml
project_name: ryuk
env:
  - CURRENT_TIMESTAMP={{ time "2006-01-02T15:04:05Z07:00" }}
before:
  hooks:
  - go mod tidy
gomod:
  # Proxy a module from proxy.golang.org, making the builds verifiable.
  # This will only be effective if running against a tag. Snapshots will ignore
  # this setting.
  # Notice: for this to work your `build.main` must be a package, not a `.go` file.
  proxy: true

  # If proxy is true, use these environment variables when running `go mod`
  # commands (namely, `go mod tidy`).
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org

  # Sets the `-mod` flag value.
  mod: mod
builds:
- env: [CGO_ENABLED=0]
  id: ryuk
  binary: ryuk
  goos:
  - linux
  goarch:
  - arm64
  - ppc64le
  - s390x
  mod_timestamp: "{{ .CommitTimestamp }}"
dockers:
- image_templates: ["docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-arm64"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm64
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mdelapenya/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mdelapenya/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ .Env.CURRENT_TIMESTAMP }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

- image_templates: ["docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-armv7"]
  goarch: arm64
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/arm/v7
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mdelapenya/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mdelapenya/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ .Env.CURRENT_TIMESTAMP }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

- image_templates: ["docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-ppc64le"]
  goarch: ppc64le
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/ppc64le
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mdelapenya/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mdelapenya/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ .Env.CURRENT_TIMESTAMP }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

- image_templates: ["docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-s390x"]
  goarch: s390x
  dockerfile: Dockerfile
  use: buildx
  build_flag_templates:
  - --platform=linux/s390x
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/mdelapenya/{{ .ProjectName }}
  - --label=org.opencontainers.image.source=https://github.com/mdelapenya/{{ .ProjectName }}
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ .Env.CURRENT_TIMESTAMP }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=MIT

docker_manifests:
- name_template: docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}
  image_templates:
  - docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-arm64
  - docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-armv7
  - docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-ppc64le
  - docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-s390x
- name_template: docker.io/mdelapenya/{{ .ProjectName }}:latest
  image_templates:
  - docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-arm64
  - docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-armv7
  - docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-ppc64le
  - docker.io/mdelapenya/{{ .ProjectName }}:{{ .Version }}-linux-s390x
