name: Build multi-arch Docker Image

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KO_DOCKER_REPO: "docker.io/testcontainers/ryuk"
      KO_DEFAULTBASEIMAGE: "gcr.io/distroless/static:nonroot"
      KO_DEFAULTBASEIMAGE_WIN: "mcr.microsoft.com/windows/nanoserver:ltsc2022"

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - run: go version

    - name: Verify project
      run: make verify

    - uses: imjasonh/setup-ko@v0.6

    - name: "Set Docker images create time"
      run: echo "SOURCE_DATE_EPOCH=$(date +%s)" >> $GITHUB_ENV

    - name: "Cross-Build images"
      run: ko build --platform=linux/amd64,linux/arm64
