# .github/workflows/goreleaser.yml
name: goreleaser

on:
  push:
    tags:
      - '*'
    branches:
      - 'mdelapenya-namespace'

env:
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  GO_VERSION: "1.18.x"

permissions:
  contents: write

jobs:
  goreleaser-linux-amd64:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist -f .goreleaser-linux-amd64.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  goreleaser:
    needs: goreleaser-linux-amd64
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist -f .goreleaser-${{ matrix.os }}.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
